@startuml ApplicationInfrastructure
!theme aws-orange

node "Digital Ocean Infrastructure" {
    node "VPS Frontend" {
        [Caddy FE]
        node "Docker FE" {
            [Svelte Frontend]
        }
    }
    node "VPS Backend" {
        [Caddy BE]
        node "Docker BE" {
            [NestJS Backend]
        }
    }
    [MongoDB Database]
    [DNS]
}

node "IAC & Automation" {
    [Terraform]
    [Github Actions]
}

node "Domain Management" {
    [host-age.ro]
    [expensy.ro domain]
    [Let's Encrypt Certificates]
}

[DNS] --> [Caddy FE] : points to
[DNS] --> [Caddy BE] : points to
[Caddy BE] --> [Docker BE] : forwards to
[NestJS Backend] --> [MongoDB Database] : manipulates
[Caddy FE] --> [Docker FE] : forwards to
[Svelte Frontend] --> [Caddy BE] : interacts with
[Terraform] -left-> [Digital Ocean Infrastructure] : provisions
[Github Actions] --> [Terraform] : triggers
[host-age.ro] --> [expensy.ro domain] : provides
[expensy.ro domain] --> [Digital Ocean Infrastructure] : points NS
[Caddy FE] --> [Let's Encrypt Certificates] : issues
[Caddy BE] --> [Let's Encrypt Certificates] : issues
[Caddy FE] --> [Let's Encrypt Certificates] : serves
[Caddy BE] --> [Let's Encrypt Certificates] : serves

@enduml
