@startuml ApplicationInfrastructure
!theme aws-orange

node "Digital Ocean Infrastructure" {
    node "VPS Frontend" {
        [nginx FE]
        node "Docker FE" {
            [Svelte Frontend]
        }
    }
    node "VPS Backend" {
        [nginx BE]
        node "Docker BE" {
            [NestJS Backend]
        }
    }
    [Database]
    [DNS]
}

node "IAC & Automation" {
    [Terraform]
    [Github Actions]
}

node "Domain Management" {
    [host-age.ro]
    [expensy.ro domain]
    [Let's Encrypt Certificates]
    [certbot]
}

[DNS] --> [nginx FE] : points to
[DNS] --> [nginx BE] : points to
[nginx BE] --> [Docker BE] : forwards to
[NestJS Backend] --> [Database] : manipulates
[nginx FE] --> [Docker FE] : forwards to
[Svelte Frontend] --> [nginx BE] : interacts with
[Terraform] -left-> [Digital Ocean Infrastructure] : provisions
[Github Actions] --> [Terraform] : triggers
[host-age.ro] --> [expensy.ro domain] : provides
[expensy.ro domain] --> [Digital Ocean Infrastructure] : points NS
[certbot] --> [Let's Encrypt Certificates] : issues
[nginx FE] --> [Let's Encrypt Certificates] : serves
[nginx BE] --> [Let's Encrypt Certificates] : serves

@enduml
