name: Publish Docker Image (Frontend)

on: 
    push:
        paths: 
            - .github/workflows/frontend-docker.yml
            - speedpulse/website

jobs:
    build_docker:
        runs-on: ubuntu-latest
        name: Build Docker Image
        steps:
            - name: Clone repository
              uses: actions/checkout@v4

            - name: Setup docker buildx
              uses: docker/setup-buildx-action@v3.7.1

            - name: Setup node.js
              uses: actions/setup-node@v4
              with:
                node-version: 'latest'

            - name: Fetch app version
              working-directory: frontend
              id: fetch_version
              run: |
                VERSION=$(jq -r '.version' package.json)
                echo "version=${VERSION}" >> $GITHUB_OUTPUT

            - name: Login to GHCR
              uses: docker/login-action@v3.3.0
              with:
                registry: ghcr.io
                username: vlsts
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build docker image
              uses: docker/build-push-action@v6.10.0
              with:
                context: frontend
                file: frontend/Dockerfile
                push: true
                labels: |
                  org.opencontainers.image.source=https://github.com/vlsts/expensy
                  org.opencontainers.image.url=https://github.com/vlsts/expensy
                  org.opencontainers.image.title="Expensy frontend website"
                  org.opencontainers.image.description="Frontend for the Expensy project."
                tags: ghcr.io/vlsts/expensy-frontend:latest,ghcr.io/vlsts/expensy-frontend:${{ steps.fetch_version.outputs.version }}
